learning_templates/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

#TEMPLATE TAGGING
app_name ='base_app' #django recognises this
urlpatterns =[
 path('relative/', views.relative, name ='relative'),
 path('other/',views.other, name ='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('',views.index, name = 'index'),
    #path('other/', views.other, name ='other'),
    #path('relative/', views.relative, name ='relative'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict ={'text':'hello world','number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class = "navbar navbar-default navbar-static-top">
    <div class="container">
     <ul class = "nav navbar-nav">
       <li ><a class ="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
       <li> <a class = "navbar-link" href="{% url 'admin:index' %} ">Admin</a></li>
       <li> <a class = "navbar-link" href="{% url 'base_app:other' %}">Other page</a></li>
     </ul>
    </div>
    </nav>

   <div class="container">
     {% block body_block %}
       <!-- Anything outside this block is extended in other pages -->
     {% endblock %}
   </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
 {% extends "basic_app/base.html" %}
 {% block body_block %}
     <h1>Welcome to index</h1>
     <h2>This is index.html page showing</h2>
     <h3>{{ text|upper }}</h3><br>
     <h3>{{ number|add:'99' }}</h3>
     <h3>{{ text|cut:'hello' }}</h3><br>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to other</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Welcome to relative URL templates</h1>
 <a href="{% url 'base_app:other' %}">link to other</a><br>
 <a href="{% url 'admin:index' %}"> link to admin</a> <br>
 <a href="{% url 'index' %}">link to index</a>
  </body>
</html>